# Generated by Django 4.2.6 on 2023-10-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsersystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='nd_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='not_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
