# Generated by Django 4.2.6 on 2023-10-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsersystem', '0003_alter_items_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='res_id',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
