# Generated by Django 4.2.6 on 2023-10-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsersystem', '0004_alter_items_res_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='s_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
